"""added the duration,title and description fields in the Session Record table 

Revision ID: 0e7b48f37baa
Revises: 244131f70607
Create Date: 2025-12-23 13:12:02.382074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e7b48f37baa'
down_revision: Union[str, Sequence[str], None] = '244131f70607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessionrecords', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True))
    op.add_column('sessionrecords', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    op.add_column('sessionrecords', sa.Column('duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessionrecords', 'duration')
    op.drop_column('sessionrecords', 'description')
    op.drop_column('sessionrecords', 'title')
    # ### end Alembic commands ###
