"""remove the required property for the speech_text fields 

Revision ID: 276aa3d42603
Revises: 8524fc75468f
Create Date: 2025-12-21 20:00:43.167740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276aa3d42603'
down_revision: Union[str, Sequence[str], None] = '8524fc75468f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'speech_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'speech_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
