"""added the report field in the session report model 

Revision ID: 2c8bcf64b439
Revises: 9366eb346113
Create Date: 2025-12-27 21:13:09.737343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c8bcf64b439'
down_revision: Union[str, Sequence[str], None] = '9366eb346113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessionreports', sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessionreports', 'report')
    # ### end Alembic commands ###
