"""added the session Report model not completed but only have an transciption fields for now

Revision ID: 56b18615ef66
Revises: 0e7b48f37baa
Create Date: 2025-12-23 15:29:44.863686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b18615ef66'
down_revision: Union[str, Sequence[str], None] = '0e7b48f37baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
