"""remove the nullable attribute from the User.avatar model

Revision ID: dfb2c53bdd89
Revises: 0969daca6963
Create Date: 2025-12-12 01:24:56.977976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb2c53bdd89'
down_revision: Union[str, Sequence[str], None] = '0969daca6963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
