"""removed the title and description fields form the SessionRecords Model instead getting form SessionReport model 

Revision ID: ffc533564289
Revises: 2c8bcf64b439
Create Date: 2025-12-30 18:43:50.311583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc533564289'
down_revision: Union[str, Sequence[str], None] = '2c8bcf64b439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessionrecords', 'title')
    op.drop_column('sessionrecords', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessionrecords', sa.Column('description', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('sessionrecords', sa.Column('title', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
